-- Challenge
-- 1. List the number of films per catagory.
select count(film.film_id) as num_of_film, film_category.category_id from film
inner join film_category on film.film_id = film_category.film_id
group by film_category.category_id;

-- 2. Retrieve the store ID, City, and country for each store.
select store.store_id, city.city, country.country
from store 
join city on store.last_update = city.last_update
join country
on country.country_id = city.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
select sum(payment.amount), store.address_id
from payment
inner join store on payment.last_update = store.last_update
group by store.address_id;

-- 4. Determine the average running time of films for each category.
select avg(film.length) as avg_film, film_category.category_id
from film
inner join film_category on film.film_id = film_category.film_id
group by film_category.category_id;

